{{- if .Values.route.enabled -}}
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ template "rocketchat.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "rocketchat.name" . }}
    helm.sh/chart: {{ include "rocketchat.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  {{- with .Values.route.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: {{ .Values.host }}
  {{- if .Values.route.tls }}
  tls:
    {{- toYaml .Values.route.tls | nindent 4 }}
  {{- else }}
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  {{- end }}
  to:
    kind: Service
    name: {{ template "rocketchat.fullname" . }}
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None
{{- end }}
